on: 
  push:
    branches:
      - master

name: "🏗 Build"

jobs:
  build-linux:
    name: "🏗 Linux build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/build-frontend
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-0-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --target x86_64-unknown-linux-gnu --release
      # - run: zip x86_64-unknown-linux-gnu.zip target/x86_64-unknown-linux-gnu/release/downcat
      - uses: actions/upload-artifact@v3
        with:
          name: x86_64-unknown-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/downcat
  
  build-windows:
    name: "🏗 Windows build"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/build-frontend
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-0-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --target x86_64-pc-windows-msvc --release
      # - run: Compress-Archive .\target\x86_64-pc-windows-msvc\release\downcat.exe x86_64-pc-windows-msvc.zip
      #   shell: pwsh
      - uses: actions/upload-artifact@v3
        with:
          name: x86_64-pc-windows-msvc
          path: target/x86_64-pc-windows-msvc/release/downcat.exe

  # build-macos:
  #   name: "🏗 MacOS build"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: sudo apt install zip
  #     - uses: ./actions/build-frontend
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         target: x86_64-apple-darwin
  #         override: true
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         use-cross: false
  #         command: build
  #         args: --target x86_64-apple-darwin --release
  #     - run: zip x86_64-apple-darwin.zip target/x86_64-apple-darwin/release/downcat
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: x86_64-apple-darwin.zip
  #         path: x86_64-apple-darwin.zip
